from __future__ import print_function
import requests, json

## default port for bitcoin testnet
## (change to 8332 for 'main net'),
rpcPort = 18333
rpcUser = 'dim'
## not a real password
## but if you use the random password generated by bitcoind
## your password should look something like this
rpcPassword = 'dim'
serverURL = 'http://' + rpcUser + ':' + rpcPassword + '@localhost:' + str(rpcPort)

headers = {'content-type': 'application/json'}
payload = json.dumps({"method": 'getblock', "params": ["0000000000005e5fd51f764d230441092f1b69d1a1eeab334c5bb32412e8dc51"], "jsonrpc": "2.0"})
response = requests.post(serverURL, headers=headers, data=payload)
print(response.json()['result'])
